<?php
/**
 * Platform console setup (CLI)
 *
 * Creates platform/config.php with a hashed super-admin password.
 *
 * Usage:
 *   php platform/setup.php <username> <password> [--no-host-restrict]
 */

if (PHP_SAPI !== 'cli') {
	exit('Run this from the command line.');
}

$argv = $_SERVER['argv'];

$username = isset($argv[1]) ? $argv[1] : '';
$password = isset($argv[2]) ? $argv[2] : '';
$restrict = !in_array('--no-host-restrict', $argv, true);

if ($username === '' || $password === '') {
	fwrite(STDERR, "Usage: php platform/setup.php <username> <password> [--no-host-restrict]\n");
	exit(1);
}

$hash = password_hash($password, PASSWORD_DEFAULT);

$contents = "<?php\n" .
	"// Generated by platform/setup.php\n" .
	"define('PLATFORM_USERNAME', " . var_export($username, true) . ");\n" .
	"define('PLATFORM_PASSWORD_HASH', " . var_export($hash, true) . ");\n" .
	"define('PLATFORM_RESTRICT_HOST', " . ($restrict ? 'true' : 'false') . ");\n";

$target = __DIR__ . '/config.php';
if (file_put_contents($target, $contents) === false) {
	fwrite(STDERR, "Error: could not write $target\n");
	exit(1);
}

echo "Wrote $target\n";
echo "Super-admin user: $username\n";
echo "Host restriction: " . ($restrict ? 'on' : 'off') . "\n";
